### ISSUE TITLE
Macaws Roof biome's o plenty Mod Loading Fails Causing crash on start-up 

### ISSUE THREAD

**Issue by DarkestDread** [Samlegamer/Macaw-s-Roofs-Compat#11]
I sent a Crash report to the original macaw because I thought they were the author of this mod the link to this report is below. 
 https://github.com/sketchmacaw/MacawsModsIssues/issues/227 
 
 The Macaws Roofs – BOP needs to upgrade to the same version to match Macaw’s Roofs.

**Comment by Samlegamer** [comment]
the mod has been developed with the latest version of forge 36.2.39

**Comment by ModernGamingWorld** [comment]
@Samlegamer I also had a crash where the 9/02/22 version of Macaw's Roofs causes this mod to crash

**Comment by Samlegamer** [comment]
fixed in macawsroofsbop-1.16.5-1.4
