### ISSUE TITLE
BYG compat crashes on client/server start-up.

### ISSUE THREAD

**Issue by ccessarr** [Samlegamer/Macaw-s-Roofs-Compat#15]
This happens with another mod too but when I try to play, at some point of the loading, it just crashes saying:
`Macaw's Roof - BYG (macawsroofbyg) has failed to load correctly`
`java.lang.NoClassDefFoundError: com/mcwroofs/kikoz/objects/roofs/RoofBlock`
And wont let me go to the main menu.

Here's a screenshot:
![imagen](https://user-images.githubusercontent.com/83140452/189533725-cf730833-fb77-4dfd-bb43-b9ef4d3dccc9.png)

Crash log: https://pastebin.com/raw/s26YiMMi

Minecraft version: 1.16.5
Forge version: 36.2.39
Server software: Mohist

Mod list: https://pastebin.com/raw/aGNbUKHt

**Comment by Samlegamer** [comment]
the pastebin is private

**Comment by ccessarr** [comment]
Oops sorry, should be public now.

**Comment by Samlegamer** [comment]
They are still not public.
But otherwise I tried the latest version 1.16.5 with these mods:
byg-1.3.5
macawsroofsbyg-1.16.5-1.5
mcw-roofs-2.2.0-mc1.16.5-forge

**Comment by ccessarr** [comment]
[crash-2022-09-11_15.46.20-fml.txt](https://github.com/Samlegamer/Macaw-s-Roofs-Compat/files/9542854/crash-2022-09-11_15.46.20-fml.txt)
Theres the crash log, maybe it's another mod causing the mod to crash?

**Comment by ccessarr** [comment]
Issue solved, thanks for the help.
