### ISSUE TITLE
Roofs dont work in Version 1.18.2

### ISSUE THREAD

**Issue by f0kx** [Samlegamer/Macaw-s-Roofs-Compat#18]
All the Roofs dont have a recipe.
Version : macawsroofsbop-1.18.2-1.2
Roof Version: mcw-roofs-2.2.0-mc1.18.2-forge

**Comment by Samlegamer** [comment]
fixed in macawsroofsbop-1.18.2-1.3

**Comment by f0kx** [comment]
thx
