### ISSUE TITLE
No Upside-Down Blockstate for 1 Roof

### ISSUE THREAD

**Issue by Adderino** [Samlegamer/Macaw-s-Roofs-Compat#20]
All but the "normal" roof block have an upside-down blockstate.
To describe more in depth the blocks "Lower Roof", "Steep Roof", "Upper Lower Roof" and "Upper Steep Roof" have upside-down blockstates but not "Roof"

Mod versions
Compat Biomes you'll go 1.0
Compat Biomes o' plenty 1.2
Biomes o plenty 17.1.1.162
Biomes you'll go 2.0.0.13

Minecraft 1.19.2
Forge 43.2.3

**Comment by Samlegamer** [comment]
Fixed 
![2023-01-19_18 16 42](https://user-images.githubusercontent.com/83614614/213518385-d79a2088-b552-4a8c-9f7e-2ca56c5a2896.png)
