### ISSUE TITLE
[1.16.5] Freezes the game.

### ISSUE THREAD

**Issue by MagmaSlime123** [Samlegamer/Macaw-s-Roofs-Compat#22]
Title. No report is created since I'm forced to kill the game upon it freezing. A log file and modlist is all I can provide.

debug.log: https://pastebin.com/BP7jkAbx
latest.log: https://pastebin.com/4T6TdWVv

![image](https://user-images.githubusercontent.com/51277766/215295346-b66868aa-741f-43e3-a4af-28c59b2341d9.png)

*If 1.16 is no longer supported, please remove it from Curse or put a notice in the description. At least this isn't 1.13 and 1.12.*

If both of these are dead, please remove them.

**Comment by sketchmacaw** [comment]
To resolve this issue, you need to update the blockstates to the new format I've made samlegamer.
The old multipart causes memory issues, crashing, freezing etc..

**Comment by Samlegamer** [comment]
bop patch available
