### ISSUE TITLE
1.19.2 breaks rendering in server

### ISSUE THREAD

**Issue by ink717** [Samlegamer/Macaw-s-Roofs-Compat#23]
Minecraft 1.19.2 Forge 43.2.4 using the newest mod builds

when trying to use worldedit to fill an area into macaw's roof, the block will be "invisible" to other players, and I can't see it myself either. We have to teleport far away and come back to make the most recent changes to show up correctly.

This doesn't happen in single-player world.

ALSO: whenever this render issue happens, this message spam the console (on client only)

I've attached the latest.log.
The very last few lines were what happens when trying to use worldedit to fill a selection into an ABSE blocks.

[latest.log](https://github.com/Samlegamer/Macaw-s-Roofs-Compat/files/10830542/latest.log)

**Comment by Samlegamer** [comment]
Have you tried the Macaw's Roofs Classic blocks?

**Comment by ink717** [comment]
We further tracked down the issue and it’s a Mojang issue instead of any mods. Thanks!
