### ISSUE TITLE
Is normal that MCW Roofs BYG consums 2GB of Ram? - 1.18.2 Forge

### ISSUE THREAD

**Issue by 5stigma** [Samlegamer/Macaw-s-Roofs-Compat#24]
Describe the bug
What the title says

Mod name & Minecraft Version and Modloader

Forge 1.18.2 - 40.2.0
MCW Roofs BYG last version 1.18.2

To Reproduce

Run the Game
Done

Thank for your attention.

**Comment by 5stigma** [comment]
https://github.com/sketchmacaw/MacawsModsIssues/issues/283

**Comment by Samlegamer** [comment]
Normally fixed in macawsbridgesbyg-1.18.2-1.4
