### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by reddragonds** [Samlegamer/Macaw-s-Roofs-Compat#28]
Greetings. There was a fashion malfunction. Perhaps because of mod conflicts, since if you run only 1 of this mod, then everything works stably. But if it is in the assembly, then the logs refer to it. 
[crash-2024-08-28_22.57.20-client.txt](https://github.com/user-attachments/files/16788366/crash-2024-08-28_22.57.20-client.txt)

**Comment by Samlegamer** [comment]
Macaw's Roofs is not installed https://legacy.curseforge.com/minecraft/mc-mods/macaws-roofs/files/5554923
