### ISSUE TITLE
Roof blocks bugs

### ISSUE THREAD

**Issue by CrusaderRabbit** [Samlegamer/Macaw-s-Roofs-Compat#3]
Roof blocks do not drop when broken and give xray when placed under other blocks.

**Comment by Samlegamer** [comment]
Which compatibility do you use?

**Comment by CrusaderRabbit** [comment]
I am using:

Macaws Roofs Compat: macawsroofsbyg-1.18.1-1.0
Macaws Roofs:               mcw-roofs-2.1.0-mc1.18.1
Terrablender:                  TerraBlender-forge-1.18.1-1.1.0.73
Oh the Biomes:               Oh The Biomes You'll Go-forge-1.18.1-1.3.5.10

**Comment by Samlegamer** [comment]
Oops I had put the loot blocks in the wrong folder.

**Comment by Samlegamer** [comment]
And I realize that this is also the case on other projects  😑

**Comment by CrusaderRabbit** [comment]
Well just glad we discovered it :)

**Comment by Samlegamer** [comment]
Fixed in 1.18.1-1.1
