### ISSUE TITLE
Lower top roof blocks rotating incorrectly  

### ISSUE THREAD

**Issue by Togeluck** [Samlegamer/Macaw-s-Roofs-Compat#5]
When lower top roof blocks are placed at a corner, the corner block will face outwards instead of inwards unlike the corner pieces in the base mod. 
Example images:
![image](https://user-images.githubusercontent.com/82799734/168252385-695f27ea-8a70-4286-b51a-413529eb1150.png)
vs
![image](https://user-images.githubusercontent.com/82799734/168252508-c948e6f1-918e-45f8-b07e-0b92c0879990.png)

**Comment by Samlegamer** [comment]
fixed in :
macawsroofsbop-1.16.5-1.3
macawsroofsbop-1.18.2-1.1
macawsroofsbop-1.19-1.1
macawsroofsbop-1.19.2-1.0
