### ISSUE TITLE
Unblock for third-party launchers

### ISSUE THREAD

**Issue by ExistingExpert** [Samlegamer/Macaw-s-Roofs-Compat#8]
May I ask why this mod was blocked for third-party launchers? I can only assume it was so that CF's download statistics are not messed up. Can this mod be unblocked? Many people don't, or straight up **can't** use Overwolf's launcher due to privacy concerns, and the fact that it is not available for linux (it only supports WOW). Due to this people have to manually download this mod everytime from the website (which, imo, is pretty meh) and forgo automatic updates for good.
![image](https://user-images.githubusercontent.com/71560815/174949773-9e6c45be-1332-4672-a9fa-a9d15eecd663.png)

**Comment by Samlegamer** [comment]
I did this for all mods
